class Assets {
    constructor() {
        this.characterSelect = document.createElement('img');
        this.characterSelect.src = 'img/characterSelect.png';
        this.characterSelectP1 = document.createElement('img');
        this.characterSelectP1.src = 'img/charSelectCursorP1.png';
        this.characterSelectP2 = document.createElement('img');
        this.characterSelectP2.src = 'img/charSelectCursorP2.png';
        this.characterSelectCPU = document.createElement('img');
        this.characterSelectCPU.src = 'img/charSelectCursorCPU.png';
        this.btnRematch = document.createElement('img');
        this.btnRematch.src = 'img/btnrematch.png';
        this.btnvsplayer = document.createElement('img');
        this.btnvsplayer.src = 'img/btnvsplayer.png';
        this.btnvsplayerdisabled = document.createElement('img');
        this.btnvsplayerdisabled.src = 'img/btnvsplayerdisabled.png';
        this.btnvscomputer = document.createElement('img');
        this.btnvscomputer.src = 'img/btnvscomputer.png';
        this.btnpractice = document.createElement('img');
        this.btnpractice.src = 'img/btnpractice.png';
        this.btnreturntomenu = document.createElement('img');
        this.btnreturntomenu.src = 'img/btnreturntomenu.png';
        this.btncharacterselection = document.createElement('img');
        this.btncharacterselection.src = 'img/btncharacterselection.png';
        this.menucursor = document.createElement('img');
        this.menucursor.src = 'img/menucursor.png';
        this.layer0 = document.createElement('img');
        this.layer0.src = 'img/layer0.png';
        this.layer1 = document.createElement('img');
        this.layer1.src = 'img/layer1.png';
        this.layer2 = document.createElement('img');
        this.layer2.src = 'img/layer2.png';
        this.layer3 = document.createElement('img');
        this.layer3.src = 'img/layer3.png';
        this.hudmugshot = document.createElement('img');
        this.hudmugshot.src = 'img/hudMugshot.png';
        this.hudlife = document.createElement('img');
        this.hudlife.src = 'img/hudLife.png';
        this.scoreImg = document.createElement('img');
        this.scoreImg.src = 'img/score.png';
        this.winScore = document.createElement('img');
        this.winScore.src = 'img/winScore.png';
        this.timerNumbers = document.createElement('img');
        this.timerNumbers.src = 'img/numbers2.png';
    }
}